### ISSUE TITLE
Cannot access to Delta class.

### ISSUE THREAD

**Issue by dddddommm** [goxr3plus/FX-BorderlessScene#11]
Hello goxr3plus!
I try to get instances of Delta class through BorderlessScene#getWindowedSize() and BorderlessScene#getWindowedPositon() methods.
These methods are available public access, but Delta class is not public.

Thanks.

**Comment by goxr3plus** [comment]
Ouuu why you want to do that :)? I mean i can make it public if it is so important :) Or you can like copy the code of it and make your own class.

You want me to make it public :)?

**Comment by goxr3plus** [comment]
@ts83989854  You have to tell me my friend or i will close the issue ...
