### ISSUE TITLE
removeDefaultCSS() on BorderScene causes java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Marcoral** [goxr3plus/FX-BorderlessScene#16]
It's me again. After update to version 4.1.0, method removeDefaultCSS() from BorderScene, started to throw java.lang.IndexOutOfBoundsException.

How to reproduce:
Run com.goxr3plus.fxborderlessscene.application.Main, but add `borderlessScene.removeDefaultCSS()` in 28th line of file (just after object creation).
It will throw an exception mentioned above.

I've solved this problem on my own - you can just merge [my branch](https://github.com/goxr3plus/FX-BorderlessScene/pull/15) with master.

**Comment by goxr3plus** [comment]
Oups i forgot about it.

**Comment by goxr3plus** [comment]
Merged Pull Request.
