### ISSUE TITLE
Adding a way to restore the screen, such as how minimize and maximize work.

### ISSUE THREAD

**Issue by bwcsemaj** [goxr3plus/FX-BorderlessScene#8]
I don't know the best way to go about this but I think there should be a feature where you can call a method to restore the screen to it's original size after being minimized or maximized. From the code it already looks like it keeps track of the last position and size and uses this to restore in the minimize but I think that part of the code could be it's own seperate part.

Even when maximizing and then you drag the move control, it auto restores to the original size. Again I think this code could be put into it's own method that can be called upon at will.

Or you could expose the previous point and size but I don't think this is probably that great of an idea. I don't know if it is already exposed either.

**Comment by goxr3plus** [comment]
Hmmm that's a great idea would you like to play with the code to implement that? Come on show me, it's not that hard. :) I will help you.

**Comment by goxr3plus** [comment]
@bwcsemaj  Well i think i have to do it then .....
